include: package:lint/analysis_options.yaml
analyzer:
  exclude:
    - build
  errors:
    constant_identifier_names: ignore
    non_constant_identifier_names: ignore

lint:
  rules:
    - prefer_single_quotes
