name: CoronaDOOM
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  uuid: 2.1.0
  vector_math: 2.0.8
  # flutter_auth_buttons: 0.8.0
  firebase_auth: 0.16.1
  cloud_firestore: 0.13.7
  # google_sign_in: 4.5.1
  audioplayers: 0.15.1
  firebase_core: 0.4.5
  flutter_dotenv: 2.1.0
  arcore_flutter_plugin:
    git:
      url: git://github.com/giandifra/arcore_flutter_plugin.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 1.10.0
  flutter_launcher_icons: 0.7.5
  lint: 1.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/corona.png
    - assets/icon.png
    - assets/idle.wav
    - assets/game-over.wav
    - .env

flutter_icons:
  image_path: "assets/icon.png"
  android: "launcher_icon"
  ios: true
